### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by tomasgreen** [appcorn/SITHSManager#1]
HI!

Seems like the pod does not compile using Xcode 10 with latest SDK (although using swift 4.0). Don't think I need to go in to details.

**Comment by appcorn** [comment]
Hi @tomasgreen! Sorry for not getting back to you until now. This project is not actively maintained, but we've just gotten acceptance to upgrade this project to the latest version of Swift and the iOS SDK. We will begin working on this ASAP.

**Comment by appcorn** [comment]
This has been fixed as of version 1.2.0
